function toInt(value, fallback) {
  const parsed = Number.parseInt(String(value ?? ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

const LOGIN_TIMEOUTS = Object.freeze({
  AUTH_PAGE_WAIT_MS: toInt(process.env.ADOBE_LOGIN_AUTH_WAIT_MS, 20000),
  EMAIL_INPUT_WAIT_MS: toInt(process.env.ADOBE_LOGIN_EMAIL_WAIT_MS, 25000),
  PASSWORD_URL_WAIT_MS: toInt(process.env.ADOBE_LOGIN_PASSWORD_WAIT_MS, 30000),
  SCREEN_DETECT_MS: toInt(process.env.ADOBE_LOGIN_SCREEN_DETECT_MS, 10000),
  OTP_TOTAL_WAIT_MS: toInt(process.env.ADOBE_LOGIN_OTP_WAIT_MS, 60000),
  FINAL_REDIRECT_WAIT_MS: toInt(process.env.ADOBE_LOGIN_FINAL_REDIRECT_WAIT_MS, 45000),
  OTP_POLL_INTERVAL_MS: toInt(process.env.ADOBE_LOGIN_OTP_POLL_INTERVAL_MS, 2000),
  OTP_INITIAL_WAIT_MS: toInt(process.env.ADOBE_LOGIN_OTP_INITIAL_WAIT_MS, 1500),
  SMALL_WAIT_MS: toInt(process.env.ADOBE_LOGIN_SMALL_WAIT_MS, 500),
  MEDIUM_WAIT_MS: toInt(process.env.ADOBE_LOGIN_MEDIUM_WAIT_MS, 1500),
  LARGE_WAIT_MS: toInt(process.env.ADOBE_LOGIN_LARGE_WAIT_MS, 2500),
  EMAIL_SUBMIT_SETTLE_MS: toInt(
    process.env.ADOBE_LOGIN_EMAIL_SUBMIT_SETTLE_MS,
    2500
  ),
  POST_OTP_SETTLE_MS: toInt(process.env.ADOBE_LOGIN_POST_OTP_SETTLE_MS, 2200),
  EMAIL_STEP_WAIT_MS: toInt(process.env.ADOBE_LOGIN_EMAIL_STEP_WAIT_MS, 18000),
  SCREEN_RECHECK_WAIT_MS: toInt(
    process.env.ADOBE_LOGIN_SCREEN_RECHECK_WAIT_MS,
    1200
  ),
  PASSWORD_INPUT_WAIT_MS: toInt(
    process.env.ADOBE_LOGIN_PASSWORD_INPUT_WAIT_MS,
    15000
  ),
  RETRY_GOTO_TIMEOUT_MS: toInt(process.env.ADOBE_LOGIN_RETRY_GOTO_TIMEOUT_MS, 60000),
  SIGN_IN_CLICK_TIMEOUT_MS: toInt(process.env.ADOBE_LOGIN_SIGN_IN_CLICK_TIMEOUT_MS, 6000),
  AUTH_REDIRECT_WAIT_MS: toInt(process.env.ADOBE_LOGIN_AUTH_REDIRECT_WAIT_MS, 20000),
  SPA_DETECT_INTERVAL_MS: toInt(process.env.ADOBE_LOGIN_SPA_DETECT_INTERVAL_MS, 1000),
  SECURITY_SKIP_CLICK_TIMEOUT_MS: toInt(process.env.ADOBE_LOGIN_SECURITY_SKIP_CLICK_TIMEOUT_MS, 8000),
  PROFILE_ACTION_WAIT_MS: toInt(process.env.ADOBE_LOGIN_PROFILE_ACTION_WAIT_MS, 2000),
  PROFILE_OTP_WAIT_MS: toInt(process.env.ADOBE_LOGIN_PROFILE_OTP_WAIT_MS, 3000),
  FINAL_STABILIZE_WAIT_MS: toInt(process.env.ADOBE_LOGIN_FINAL_STABILIZE_WAIT_MS, 1000),
});

module.exports = {
  LOGIN_TIMEOUTS,
};
