exports.up = async function up(knex) {
  await knex.raw(`
    CREATE SCHEMA IF NOT EXISTS admin;
    CREATE SCHEMA IF NOT EXISTS system_automation;

    CREATE TABLE IF NOT EXISTS admin.users (
      userid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(100) NOT NULL UNIQUE,
      passwordhash text NOT NULL,
      role varchar(50) DEFAULT 'user',
      createdat timestamptz DEFAULT now()
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_users_username_lower
      ON admin.users (lower(username));

    CREATE TABLE IF NOT EXISTS system_automation.accounts_admin (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email text NOT NULL UNIQUE,
      password_encrypted text NOT NULL,
      adobe_org_id text,
      org_name text,
      license_status text DEFAULT 'unknown',
      user_count integer DEFAULT 0,
      cookie_config text,
      otp_source text DEFAULT 'imap',
      last_checked_at timestamptz,
      is_active boolean DEFAULT true,
      created_at timestamptz DEFAULT now(),
      access_url text,
      id_product text,
      CONSTRAINT accounts_admin_otp_source_check
        CHECK (otp_source IN ('imap', 'tinyhost', 'hdsd'))
    );

    CREATE TABLE IF NOT EXISTS system_automation.list_user (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer text,
      account text,
      org_name text,
      expired date,
      status text NOT NULL DEFAULT 'chưa add',
      id_product text,
      update_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS idx_list_user_account
      ON system_automation.list_user (account);
    CREATE INDEX IF NOT EXISTS idx_list_user_expired
      ON system_automation.list_user (expired);
    CREATE INDEX IF NOT EXISTS idx_list_user_status
      ON system_automation.list_user (status);
  `);
};

exports.down = async function down(knex) {
  await knex.raw(`
    DROP SCHEMA IF EXISTS system_automation CASCADE;
    DROP SCHEMA IF EXISTS admin CASCADE;
  `);
};
